yury-fedorov/AoC

AoC17/rust/src/common.rs, AoC17/rust/src/day07.rs, AoC17/rust/src/lib.rs
Hello Yury, this is a PR to construct the collections in AoC17/rust/src/day07.rs in a more functional way (so that they don't have to be mutable). I have done it step by step, check the individual commits.
=> construct collections in a more functional way

AoC17/rust/src/day15.rs, AoC17/rust/src/tests.rs
Yury, day15 offers the opportunity to practice some concurrency.
(It actually makes the algorithm slower, but it's a nice exercise anyway...)
=> use threads in day15

AoC19/java/src/test/java/aoc19/Day16Test.java
Takes 4 h 24 m. Could be easily improved with parallelization. Magic with - 101 was added just for safety margin.
=> AoC19 part 2 solved

AoC19/java/README.md
Reviewed after day 16 is solved
=> AoC19 java/README.md

AoC19/README.md
After day 16 is completely solved
=> AoC19 README.md update

AoC19/java/src/test/java/aoc19/Day20Test.java
Simplification of maze for part1 method creation.
=> AoC19 Day20 Part 2 - initial refactoring

AoC19/java/src/test/java/aoc19/Day20Test.java
introduction of custom solution method
=> AoC19 Day20 Part 2 - preparation refactoring

AoC19/java/src/test/java/aoc19/Day20Test.java
=> AoC19 Day 20 Part 2 - preparation refactoring

AoC19/java/src/test/java/aoc19/Day20Test.java
level is used in part 2 but to keep the algorithm as much generic, let's introduce it also for the solution of part 1
=> AoC19 Day20 Part2 - level introduction

AoC19/java/src/test/java/aoc19/Day20Test.java
=> AoC 19 Day 20 Part 2 - alpha version

AoC19/java/src/test/java/aoc19/Day20Test.java
=> AoC19 Day20 Part2 solved!

AoC19/java/src/test/java/aoc19/Day17Test.java
Preparation for the proper instructions for robots
=> AoC19 Day17 Part2 - draft

AoC19/java/src/test/java/aoc19/Day18Test.java
=> AoC19 Day18 solved

AoC19/java/src/test/java/aoc19/Day22Test.java
Initial draft with shuffling functions.
=> AoC19 Day22 Part 2 - draft

AoC19/java/src/test/java/aoc19/Day22Test.java
deal with increment inverse function is still not good
=> AoC19 Day 22 Part 2 - draft inverse function 3

AoC19/java/src/test/java/aoc19/Day22Test.java
all tests are green but it is too slow
=> AoC 19 Day 22 Part 2 - alpha 1 - 2100 days to run

AoC22/cpp/day23.cpp
Result is wrong but code looks reasonable
=> AoC22 Day23 alpha

AoC22/cpp/day16.cpp
the new state related pieced to be yet integrated in the main algorithm
=> AoC22 Day16 Part1 early draft #92

AoC22/cpp/day11.cpp
=> AoC22 Day11 - portable, absl::Span, constexpr

AoC22/cpp/day19.cpp
=> AoC22 Day19 early draft

AoC22/cpp/day19.cpp
Second parts takes too much time.
=> AoC22 Day19 Part1 solved in 103 seconds

AoC22/cpp/day19.cpp
Part1 is not ending in 57 seconds
=> AoC22 Day19 Part2 alpha

AoC22/cpp/day16.cpp
Second version: changed approach of navigation
=> AoC22 Day16 early draft

AoC22/cpp/day16.cpp
Something yet is not working properly - bug fix is required
=> AoC22 Day16 alpha

AoC22/cpp/day22.cpp
Preparation refactoring to introduce logic for part 2 in less intrusive way
=> AoC22 Day22 Part2 work in progress - refactoring

AoC22/cpp/day17.cpp
=> AoC22 Day17 Part2 alpha

AoC22/cpp/common.h, AoC22/cpp/day16.cpp, AoC22/cpp/day17.cpp, AoC22/cpp/day22.cpp
Disabling red tests in the pipeline.
=> Filter out red tests

AoC22/cpp/CMakeLists.txt
https://github.com/google/re2/issues/436
=> Update CMakeLists.txt - re2 main

AoC23/data/08-1.txt, AoC23/data/08-2.txt, AoC23/go/day08/day08.go, AoC23/go/main_test.go
=> AoC23 Day08 draft
